[package]
name = "nom-reprap-response"
version = "0.1.0"
authors = ["D1plo1d <thatotherdude@gmail.com>"]
edition = "2018"

[[bench]]
name = "parse_response_benchmark"
harness = false

[dev-dependencies]
criterion = "0.3.3"
insta = "0.16.1"
toml = "0.5.6"
colored = "2.0.0"

[dependencies]
anyhow = "1.0.32"
nom = "6.0.0-alpha.1"
log = "0.4.8"
