id = "1"
modelVersion = 1

[[controllers]]
id = "1"
modelVersion = 1

  [controllers.model]
  name = "RAMPS Controller Board"
  serialPortID = "/dev/null/no-serial-port"
  automaticBaudRateDetection = true
  baudRate = "250000"
  simulate = false
  awaitGreetingFromFirmware = true
  gcodeHistoryBufferSize = 20
  delayFromGreetingToReady = 2_000
  pollingInterval = 500
  fastCodeTimeout = 30_000
  longRunningCodeTimeout = 60_000
  serialConnectionTimeout = 3_000
  responseTimeoutTickleAttempts = 3
  longRunningCodes = [ "G4", "G28", "G29", "G30", "G32", "M226", "M400", "M600" ]
  blockingCodes = [ "M0", "M1", "M21", "M109", "M116", "M190", "M191" ]
  checksumTickles = false

[[axes]]
id = "2"
modelVersion = 1

  [axes.model]
  name = "X"
  address = "x"
  feedrate = 150

[[axes]]
id = "3"
modelVersion = 1

  [axes.model]
  name = "Y"
  address = "y"
  feedrate = 150

[[axes]]
id = "4"
modelVersion = 1

  [axes.model]
  name = "Z"
  address = "z"
  feedrate = 4

[[toolheads]]
id = "5"
modelVersion = 1
type = "TOOLHEAD"

  [toolheads.model]
  name = "Extruder 1"
  address = "e0"
  heater = true
  feedrate = 3
  filamentSwapExtrudeDistance = 50
  filamentSwapFastMoveEnabled = false
  bowdenTubeLength = 0
  filamentSwapFastMoveSpeed = 100
  filamentSwapContinuousPullEnabled = false
  filamentSwapContinuousPullSpeed = 3
  beforeFilamentSwapHook = ""

[[speedControllers]]
id = "6"
modelVersion = 1

  [speedControllers.model]
  name = "Hot End Fan"
  address = "f0"

[[buildPlatforms]]
id = "7"
modelVersion = 1
type = "BUILD_PLATFORM"

  [buildPlatforms.model]
  name = "Bed"
  address = "b"
  heater = true

[[plugins]]
id = "1"
modelVersion = 1
package = "teg-core"

  [plugins.model]
  name = "New Printer"
  automaticPrinting = false
  swapXAndYOrientation = false
  beforePrintHook = ""
  afterPrintHook = ""
  pauseHook = ""
  resumeHook = ""
